### ISSUE TITLE
Feature Request: When `./data` is old and out of date apps fail to start

### ISSUE THREAD

**Issue by willp-bl** [alphagov/verify-local-startup#11]
Maybe delete it and regenerate if it's older than a week or two?

**Comment by j-maynard** [comment]
OK looks like a good feature request, it could also be classed as a bug.  This will need investigating.  I'll take this to the team, also might be worth just regenerating the data directory every time the startup script is run.

**Comment by j-maynard** [comment]
This was addressed in this PR:

https://github.com/alphagov/verify-local-startup/pull/70

Closing this issue.
