### ISSUE TITLE
Inconsistencies between ways of starting up applications

### ISSUE THREAD

**Issue by andy-paine** [alphagov/verify-local-startup#39]
Local-startup currently has:
- PKI generation
- Scripts/config for starting apps in JVM
- Scripts/config for starting apps in docker-compose (different config)
- Misc. scripts that other repos source

The intention/direction of this repository should be cleared up so that it can do one thing and do it well

**Comment by j-maynard** [comment]
@andy-paine I appreciate you might not care about this any more but I am going through the process of cleaning up the issue log for this repo.  We've done a number of changes to this repo recently. The main goal of this is allow this repo to be the gateway to running the verify-hub locally in docker using only our open source repos so anyone can run the hub locally.

I understand there is a number of what appears to be disparate parts.  We're about to start going through a process of updating the README and associated documentation for this repo which I hope will clean up some of your comments and explain why things are the way they are.
